### ISSUE TITLE
Check off the following tasks before starting the research

### ISSUE THREAD

**Issue by chunyuema** [privacy-tech-lab/gpc-privacy-choice#141]
This issue compiles all the logistic details we need to do before starting the research: 

- [x] Changing from free tier to paid tier for firebase if necessary #124
- [x] Update the Firestore rules #134 
- [x] Final review of all UI language to make schemes consistent and also ensure consistency with usability survey (@SebastianZimmeck) 
- [x] Update the services.json in the code base #130; this task is about using the most recent Disconnect list before starting the research; so, it is a one-time update
- [x] Randomize scheme assignment again (after disabling randomization for testing)
- [x] Clean out Firestore database
- [x] Create Release on GitHub (without the config file, though, the config file will be included on the Chrome Web Store)
